PROJECT = ROReservoir
USE_RF24 =1
MCU := atmega328
ARDUINO_VERSION := 10607
PORT := \\.\COM4

include ../utils/Makefile.arduino

serial:
	C:/Program\ Files\ \(x86\)/PuTTY/putty.exe -load Arduino &

-include Makefile.d
