
light_sim.exe : light_sim.cpp
	g++ -o light_sim.exe light_sim.cpp

light_sim_save.exe : light_sim_save.cpp
	g++ -o light_sim_save.exe light_sim_save.cpp

light_sim: light_sim.exe light_sim_save.exe
	./light_sim.exe

curtime : curtime.cpp
	@g++ curtime.cpp -o curtime

