PROJECT = LightFixture1
USE_RF24 =1
MCU :=atmega2560
ARDUINO_VERSION := 10607
#MCU := atmega328p
#ARDUINO_VERSION := 10607
PORT := \\.\COM5

serial:
	C:/Program\ Files\ \(x86\)/PuTTY/putty.exe -load Arduino &

include ../utils/Makefile.arduino
# DO NOT DELETE THIS LINE -- make depend depends on it.
