PROJECT = CatBox
MCU := atmega328p
ARDUINO_VERSION := 10607
PORT := \\.\COM9
UPLOAD_RATE := 57600

include ../utils/Makefile.arduino

serial:
	C:/Program\ Files\ \(x86\)/PuTTY/putty.exe -load Arduino &

-include Makefile.d
